main:
  - name: 文章
    pageRef: /posts
    weight: 10
    params:
      icon: posts

  - name: 標籤
    weight: 20
    pageRef: /tags
    params:
      icon: tags

  - name: 歸檔
    pageRef: /archives
    weight: 30
    params:
      icon: archive

  - name: 項目
    weight: 40
    pageRef: /projects
    params:
      icon: projects

social:
  - name: RSS
    url: https://clixtw.github.io/index.xml
    weight: 10
    params:
      icon: rss
      
  - name: Email
    url: mailto:a8aixy693@mozmail.com
    weight: 20
    params:
      icon: email
